### PR TITLE
Refactor the release workflow

### LINKED ISSUE #369: Unit tests not running in CI.
Not sure what happened here, but I can fix this. Doesn't look like I have permissions to fill out the assignees field either.

See here https://github.com/hpcng/warewulf/runs/5874333550?check_suite_focus=true
We are doing `make all` which does not run tests. We may want go vet as well.

### PR DESCRIPTION
**Pull request by anderbubble**
## Description of the Pull Request (PR):

- Ensure that godeps doesn't try to download packages
- Split "tidy" into separate target (This allows `make vendor` to download packages to satisfy `go.mod` without changing `go.mod`.)
- Workaround for CentOS 7 gzip (The CentOS 7 gzip doesn't have `--keep`)
- Fix use of `OFFLINE_BUILD` in warewulf.spec (warewulf.spec appears to have expected that an offline build would be requested with `--with offline`; but conditional builds are not supported by mock)
- Use a matrix for multiple builds
- Merge mockbuild.sh into release.yml
- Upload dist only once (not once per build)
- Make release package uploads more explicit (makes errors more visible)
- Configure mock to log to the runner log
- Use variables to define artifact names only once
- Target the release explicitly by id
- Run the test suite in each mock environment (fixes #369)
- Update OpenSUSE Leap build to 15.5 (15.3 is EOL and not building correctly)
- Add a Rocky Linux 9 build
- Switch to Rocky Linux 9 build container (mostly to get mock configuration for newer OpenSUSE Leap)
- Allow successful releases to complete if some releases fail (`fail-fast: false`)

### This fixes or addresses the following GitHub issues:

 - Fixes #369

#### Before submitting a PR, make sure you have done the following:

- [x] Read the [documentation for contributing to Warewulf](https://warewulf.org/docs/development/contributing/contributing.html)
- [x] Added changes to the [CHANGELOG](https://github.com/hpcng/warewulf/blob/development/CHANGELOG.md) if necessary
- [x] Updated [userdocs](https://github.com/hpcng/warewulf/tree/development/userdocs) if necessary
- [x] Based this PR against the appropriate branch (typically [development](https://github.com/hpcng/warewulf/tree/development/userdocs))
- [x] Added myself as a contributor to the [Contributors File](https://github.com/hpcng/warewulf/blob/development/CONTRIBUTORS.md)

### CODE REVIEW

**Comment by anderbubble** [comment]
I keep discovering that I've broken the release build; so I wanted to dig into it for real and make it less fragile.

I've been testing this in a fork so that I could generate test releases without disrupting here. You can see a working workflow run at https://github.com/anderbubble/warewulf/actions/runs/6446310724.

**Comment by mslacken** [comment]
Still typing two times `make` warewulf is compiled is compiled two times. I would say  without changes it should just be compiled once:
```
[chris@rocky warewulf]$ make
go mod tidy -v
go mod vendor
GOOS=linux go build -mod vendor -tags "containers_image_openpgp containers_image_ostree" -o wwctl cmd/wwctl/main.go
CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -ldflags "-extldflags -static" -o wwclient cmd/wwclient/main.go
go build -o ./wwapid internal/app/api/wwapid/wwapid.go
go build -o ./wwapic  internal/app/api/wwapic/wwapic.go
go build -o ./wwapird internal/app/api/wwapird/wwapird.go
./wwctl --emptyconf genconfig defaults >etc/defaults.conf
mkdir -p etc/bash_completion.d/
./wwctl --emptyconf genconfig completions >etc/bash_completion.d/wwctl
[chris@rocky warewulf]$ make
go mod tidy -v
go mod vendor
GOOS=linux go build -mod vendor -tags "containers_image_openpgp containers_image_ostree" -o wwctl cmd/wwctl/main.go
CGO_ENABLED=0 GOOS=linux go build -mod vendor -a -ldflags "-extldflags -static" -o wwclient cmd/wwclient/main.go
go build -o ./wwapid internal/app/api/wwapid/wwapid.go
go build -o ./wwapic  internal/app/api/wwapic/wwapic.go
go build -o ./wwapird internal/app/api/wwapird/wwapird.go
./wwctl --emptyconf genconfig defaults >etc/defaults.conf
mkdir -p etc/bash_completion.d/
./wwctl --emptyconf genconfig completions >etc/bash_completion.d/wwctl
```

**Comment by anderbubble** [comment]
@mslacken this actually broke at #945; but I've undone that change here in b164daabe19658b250ecd1616fabe5c2cf4f0c02.

**Review by mslacken — COMMENTED** [review]
If routes.proto is changed I get following error
```
internal/pkg/api/routes/wwapiv1/routes.pb.go:14:2: cannot find module providing package github.com/golang/protobuf/ptypes/empty: import lookup disabled by -mod=vendor

```

**Comment by anderbubble** [comment]
@mslacken I did make one small change that was preventing `protoc` from being downloaded when necessary; but I'm not seeing the behavior you indicated.

```shell

$ touch internal/pkg/api/routes/v1/routes.proto 
$ make
mkdir -p .tools
cd .tools && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-linux-aarch_64.zip && unzip -o protoc-24.0-linux-aarch_64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2901k  100 2901k    0     0  1697k      0  0:00:01  0:00:01 --:--:-- 3604k
Archive:  protoc-24.0-linux-aarch_64.zip
  inflating: bin/protoc              
  inflating: include/google/protobuf/any.proto  
  inflating: include/google/protobuf/api.proto  
  inflating: include/google/protobuf/compiler/plugin.proto  
  inflating: include/google/protobuf/descriptor.proto  
  inflating: include/google/protobuf/duration.proto  
  inflating: include/google/protobuf/empty.proto  
  inflating: include/google/protobuf/field_mask.proto  
  inflating: include/google/protobuf/source_context.proto  
  inflating: include/google/protobuf/struct.proto  
  inflating: include/google/protobuf/timestamp.proto  
  inflating: include/google/protobuf/type.proto  
  inflating: include/google/protobuf/wrappers.proto  
  inflating: readme.txt              
touch --no-create .tools/bin/protoc # by default the timestamp is preserved from the archive
curl -L https://github.com/grpc-ecosystem/grpc-gateway/releases/download/v2.16.2/protoc-gen-grpc-gateway-v2.16.2-linux-arm64 -o .tools/bin/protoc-gen-grpc-gateway
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7616k  100 7616k    0     0  1509k      0  0:00:05  0:00:05 --:--:-- 1909k
chmod +x .tools/bin/protoc-gen-grpc-gateway
GOBIN="/home/janderson/warewulf.git/tree/srpm/.tools/bin" go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
GOBIN="/home/janderson/warewulf.git/tree/srpm/.tools/bin" go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
PATH=.tools/bin:/home/janderson/.local/bin:/home/janderson/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin .tools/bin/protoc \
	-I /usr/include -I internal/pkg/api/routes/v1 -I=. \
	--grpc-gateway_opt logtostderr=true \
	--go_out=. \
	--go-grpc_out=. \
	--grpc-gateway_out=. \
	routes.proto
GOOS=linux go build -mod vendor -tags "containers_image_openpgp containers_image_ostree" -o wwctl cmd/wwctl/main.go
go build -o ./wwapid internal/app/api/wwapid/wwapid.go
go build -o ./wwapic  internal/app/api/wwapic/wwapic.go
go build -o ./wwapird internal/app/api/wwapird/wwapird.go
./wwctl --emptyconf genconfig defaults >etc/defaults.conf
mkdir -p etc/bash_completion.d/
./wwctl --emptyconf genconfig completions >etc/bash_completion.d/wwctl
```

I also don't see that module included in `routes.pb.go`.

```shell

$ grep 'ptypes/empty' internal/pkg/api/routes/wwapiv1/routes.pb.go
$ head -n20 internal/pkg/api/routes/wwapiv1/routes.pb.go
// Routes for the wwapi (WareWulf API).
// TODO: Try protoc-gen-doc for generating documentation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.0
// source: routes.proto

package wwapiv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)
```

**Review by mslacken — APPROVED** [review]
OK
